GET  http://localhost:3001/users

###
GET  http://localhost:3001/users/2

###
POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@gmail.com",
    "gender": "Male"
}

###
PATCH  http://localhost:3001/users/2
Content-Type: application/json

{
    "name": "Ahmad Multazam",
    "email": "multazamji@gmail.com",
    "gender": "Male"
}

###
DELETE   http://localhost:3001/users/2